name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v10
      with:
        name: siraben
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A pkgs.x86_64-darwin.emacsGccDarwin
    - run: echo OK
